name: Test Dockerized HTML Action

on:
  push:
    branches:
      - main

jobs:
  serve-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Dockerized Action
        uses: ./ # Uses the Dockerized Action in this repository
        with:
          port: 8080
